# Example: Kilocode Resolver GitHub Action
#
# Copy this file to your repository's .github/workflows/ directory
# and configure the required secrets.
#
# Required Secrets:
#   - KILOCODE_API_KEY: Your Kilocode API key from app.kilo.ai
#
# Optional Secrets:
#   - PAT_TOKEN: Personal Access Token with repo permissions (for creating PRs)
#   - PAT_USERNAME: GitHub username associated with PAT_TOKEN
#
# Usage:
#   1. Label an issue with 'fix-me' to trigger automatic resolution
#   2. Comment '@kilocode-agent' on an issue or PR (must be owner/collaborator/member)
#   3. Use in a PR review with '@kilocode-agent' mention

name: Resolve Issue with Kilocode

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-kilocode-resolver:
    # You can reference the workflow from this repository, or copy the full workflow
    # uses: zeromodern/0mod-core/.github/workflows/kilocode-resolver.yml@main
    
    # Or use the inline version below:
    if: |
      github.event.label.name == 'fix-me' ||
      (
        ((github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') &&
        contains(github.event.comment.body, '@kilocode-agent') &&
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER')
        ) ||
        (github.event_name == 'pull_request_review' &&
        contains(github.event.review.body, '@kilocode-agent') &&
        (github.event.review.author_association == 'OWNER' || github.event.review.author_association == 'COLLABORATOR' || github.event.review.author_association == 'MEMBER')
        )
      )
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Kilocode CLI
        run: npm install -g @kilocode/cli

      - name: Set environment variables
        run: |
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "ISSUE_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "ISSUE_TYPE=pr" >> $GITHUB_ENV
          elif [ -n "${{ github.event.issue.pull_request }}" ]; then
            echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
            echo "ISSUE_TYPE=pr" >> $GITHUB_ENV
          else
            echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
            echo "ISSUE_TYPE=issue" >> $GITHUB_ENV
          fi

      - name: Fetch issue details
        id: fetch_details
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = process.env.ISSUE_NUMBER;
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            core.setOutput('title', issue.title);
            core.setOutput('body', issue.body || '');

      - name: Comment start message
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[Kilocode](https://kilo.ai) started working on this! Monitor progress [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`
            });

      - name: Configure Kilocode
        env:
          KILOCODE_API_KEY: ${{ secrets.KILOCODE_API_KEY }}
        run: |
          mkdir -p ~/.kilocode
          cat > ~/.kilocode/config.json << EOF
          {
            "profiles": [
              {
                "id": "default",
                "provider": "kilocode",
                "kilocodeToken": "$KILOCODE_API_KEY",
                "kilocodeModel": "anthropic/claude-sonnet-4"
              }
            ],
            "autoApproval": {
              "enabled": true,
              "read": { "enabled": true, "outside": false },
              "write": { "enabled": true, "outside": false, "protected": true },
              "execute": {
                "enabled": true,
                "allowed": ["npm", "git", "pnpm", "yarn", "node", "npx"],
                "denied": ["rm -rf /", "sudo"]
              },
              "browser": { "enabled": false },
              "mcp": { "enabled": true },
              "mode": { "enabled": true },
              "subtasks": { "enabled": true },
              "question": { "enabled": true, "timeout": 30 },
              "retry": { "enabled": true, "delay": 10 },
              "todo": { "enabled": true }
            }
          }
          EOF

      - name: Create fix branch
        run: |
          BRANCH_NAME="kilocode-fix-${{ env.ISSUE_NUMBER }}-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Run Kilocode
        env:
          KILOCODE_API_KEY: ${{ secrets.KILOCODE_API_KEY }}
        run: |
          PROMPT="Fix issue: ${{ steps.fetch_details.outputs.title }}

          ${{ steps.fetch_details.outputs.body }}"
          
          echo "$PROMPT" | kilocode --auto --timeout 600 || true

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || github.token }}
        run: |
          git config user.name "kilocode-agent"
          git config user.email "kilocode-agent@users.noreply.github.com"
          git add -A
          git commit -m "fix: resolve issue #${{ env.ISSUE_NUMBER }}"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git push -u origin "${{ env.BRANCH_NAME }}"

      - name: Create PR
        if: steps.check_changes.outputs.has_changes == 'true'
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN || github.token }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `fix: resolve issue #${process.env.ISSUE_NUMBER}`,
              body: `Automated fix for #${process.env.ISSUE_NUMBER}`,
              head: process.env.BRANCH_NAME,
              base: 'main',
              draft: true
            });
            core.setOutput('pr_number', pr.number);
            core.setOutput('pr_url', pr.html_url);

      - name: Comment result
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const hasChanges = '${{ steps.check_changes.outputs.has_changes }}' === 'true';
            const prNumber = '${{ steps.create_pr.outputs.pr_number }}';
            
            let body;
            if (hasChanges && prNumber) {
              body = `✅ Fix generated! Review PR #${prNumber}`;
            } else if (hasChanges) {
              body = `⚠️ Changes made but PR creation failed. Check branch: ${process.env.BRANCH_NAME}`;
            } else {
              body = `❌ Unable to generate a fix. Check [logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).`;
            }
            
            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
